14.0 d
InsanivimusOmnes/system-demo pull request #2
Opened 2022-07-20 12:38 UTC by InsanivimusOmnes

Fix and load module project enumerate

2022-07-20 13:53 UTC, geomer198 reviewed
Для функций, которые ты сам добаляешь нужно писать docstring. 
Для функций которые ты дополняешь не плохо было бы писать коментарии о том, что ты там делаешь.

2022-07-20 13:53 UTC, geomer198 commented on sales_sequence/models/sale_order_line.py
> +    def _compute_sequence_line(self):
Docstring

2022-07-21 17:06 UTC, isserver1 requested changes
См комментарии

2022-07-21 17:06 UTC, isserver1 commented on sales_sequence/tests/test_sale.py
> +        """test change lines of place"""
test line sequence change (грамматика))

2022-07-21 17:06 UTC, isserver1 commented on project_enumerate/tests/test_task_number.py
> +        self.assertEqual(
Сравнивать текстовые значения - плохая идея.
Во-первых поле name может быть переводимым, И тогда его значение будет разным в зависимости от языка пользователя. Хотя в тестах это маловероятно конечно.
Но главное - тебе нужен уникальный идентификатор. Нужно поле которое может однозначно(!) сказать: "да, это нужная запись". Вот это поле и нужно использовать, и его же проверять. 
Это касается всех тестов.

2022-07-21 17:06 UTC, isserver1 commented on sales_sequence/models/sale_order_line.py
> +    numbers = fields.Char(string="Number", compute="_compute_numbers", store=True)
Имена полей должны быть в единственном числе и не должны дублировать встроенные типы и ключевые слова
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#37models

2022-07-21 17:06 UTC, isserver1 commented on sales_sequence/models/sale_order_line.py
> +    sequence_line = fields.Char(
Какую функциональную задачу решает данное поле?

2022-07-24 12:56 UTC, isserver1 requested changes
Задание было "добавить демо данные" а не "скопировать все подряд без рабору из других модулей"

Основной вопрос ко всему - В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on sales_sequence/data/sale_demo.xml
> +        <record id="base.main_company" model="res.company">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on sales_sequence/data/sale_demo.xml
> +        <record id="base.user_demo" model="res.users">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on sales_sequence/data/sale_demo.xml
> +        <record model="crm.team" id="sales_team.team_sales_department">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on sales_sequence/data/sale_demo.xml
> +        <record model="crm.team" id="sales_team.crm_team_1">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on sales_sequence/data/sale_demo.xml
> +        <record id="utm_source_sale_order_0" model="utm.source">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on project_enumerate/data/project_demo.xml
> +        <record id="project_stage_0" model="project.task.type">
В чем смысл этой записи? Зачем тебе нужна новая статдия проекта?

2022-07-24 12:56 UTC, isserver1 commented on project_enumerate/data/project_demo.xml
> +                name="mail_template_id"
А шаблон сообщения нам зачем?

2022-07-24 12:56 UTC, isserver1 commented on project_enumerate/data/project_demo.xml
> +        <record id="project_stage_1" model="project.task.type">
В чем смысл этой записи?

2022-07-24 12:56 UTC, isserver1 commented on project_enumerate/data/project_demo.xml
> +        <record id="project_stage_2" model="project.task.type">
В чем смысл этой записи?

2024-04-09 14:40 UTC, closed without merging